sudo: required
services:
  - docker

install:
  - npm install -g dockerlint

script:
  - ./validate-dockerfiles.sh
  - ./build-images.sh

deploy:
  provider: script
  script: ./push-images.sh
  on:
    branch: master

env:
  global:
  - secure: ZOQ9293h69t7/8xI6XjdnlzRCuFpLlAEFOVsTEpF3y3ncy4NaOJKWREUNhDBorbj2IFHDZ+mcXBZD5flMXYJErewlRADulaXnqi2+wnEnYNBiqxhOwKNOasn3BB76vTT4ow5V+j1GELm5LW9ENRqvbEunx9yxO2fBpHSmkSc0rn/7720P9S2r+YOlvlbq+qbS4+zSjo0Rz0JWPWRm+puXejs5GWKIasGkyPOO8n7eBndVbd5FLpTZcVQY4f4fJGCiJ7Z6cWkU0mOeGO1kkaG+MCBAfWrNLYtnc2g+jRH1yH8mld8btdRdDrPcKhWaCnFLUSUTDIQSPIoH/85T40Q0uo2017Okya0ZiN8LgCfVhjyex27XGe+qhmnlQqkxQXpGgbC5rCUnMMdeBMYcy7bHG8XYGKVV+IU4dxcM/NxxjVQKjTXSkxyQzQVnQ5Scr/E5jWIHkrNcMSxYvgBLCKPiXaJ+xNRegAl3u8XkLNmjqp0YbTX6Pb2DMvy7TnR6TJh1E8yFzR4PXz9xwiyyEBh80cYSPotKzZ5krWZjIhdg0/6GDOb1DAqIsUZMjPKWHwVQPwnjHK2Dyc57MB+Uy1igv3+VmNbLZ3y4nDySbkqoc1ZcXjDVkZyiEMCZbzPTYGBn1KjgypPtoI+NAOuGa9ZkuuKUidML2b0vXdr+vj6NHc=
  - secure: l46lz4fm7ys6apF2aIBSK5Un2Y6rejHFbw9JIMr+XDhfvVvdzcBrmtmUP1dD9PwVUJ99wwGVjLBXXqgyps99qIGuQBKzOf/Ofr1X5yfFb3Tl2ti2s/SYsj/de5zcW2o0fFtPuU7Qe3mzTjt9+qaZFQyDjXZgF0aiMNggLmXhY13T8OvCVfNEtFI2VNkPtnhTTiX/OenFsEw4bbccneuEWSnoqUXbWv/y8WO/4TCKMYRY5u22mJ/0aPNJhjjy0TKUhTeNTr2/cUJtnP2z0e4loTdpJZPaQvCXlsOIXdFb9/03gwEF31KRNv4Ypn5KvQ/WvHNWO8WFZPHBly/RbCJBjxOsvqxw9aK9r8kXCAueafdg36898WEZ83eMSjQVyvYUyDxY0ounIG4usPIe/ox7fIdOxu6BOilS+8s7xKP3YQ5FBAWRdj66Vao2v2pm89ygTTDUNWXWdhPUTTnzA9kwnCgp2Ex6+Xtij+g9ly16k0M6AIHPa2J8nAfJlI2zUsnHh2BBco3zUtTjqXWXBF6btWhFe8TMt4IfGVw9fCkQpzCaclPeWv8m6DIM4wvUHIhPscFb8y/iXHlCtP7IuF9E9lLosuhhQm6t6kiBTdpQ+gsV5hP6o7DUwerHDSAyUGIBB+o+EKxa0yWMi0Q1oUkpshm6/d85nqRIEku9iGKuabU=
  - secure: cNXPlDOXkOTp79XMlrgCL/nJ/jnZ7KbQypvoiZDBkHnB/m5IjVCSWz7Il1oQBEcmKUo9mQlzLzgaK8v9gZqZmwltwz0ZMfQrY71Knnd9nD514noH7zIqLHYfIBKJvZaC3nnjFexoUODpynE4OuYv9W0KFy6Wy23cx9abdN0h7H3J4rZxFkaQsQ4Ojt2CJN03MNxq3npEOLh38zHwHR+vqQkzMc5v6EelrSrHT42advLauIo6OC2MOauJcLOEgqQCMGlGVfxi3vEkp3pNOLGTltA5nTCmJyR3CpyFsV0hRidbtu7qAt/RV8KOlJ0/Eqrosip+NgXIMpeJ/p2Wz3tnlyivLy21E78QPzN2v1AfFjJrx0G994BRNra3uTUiZp0I/+idXveiHmq31ElO7Ejop5i0CjMLsntnZO1DbvTED5dUUsILD1CVcarFb5xymFK/MmiCcYvGHCppIw+jMpLFcPabjXhcGWUJg5DudC2gCo9jPnNA92nSvVCcfyKJCjSTNlKEm1YwYzjfyI8Q4LEnFlKQ9wtFXhSrt9c6XvQrGlDLX+fPmMppjrLDYMDzQFKlBeGn8/9Wl87Nn61zc/y/ZwbB5k1lUTdRyrq159nCwxHlZQUDmZ/xePwZmqAz+l2IkMrc9qPy6DUjhoyVSclbbH0OFy4SeD9Xca5XKuOyHs4=
  - COMMIT=${TRAVIS_COMMIT::8}
